// Tang Nano 9K Blinker Top-Level
// This wraps the combinational modules generated by ts2v with
// sequential logic (always_ff) to create a working LED blinker.
//
// The ts2v transpiler (Milestone 1) generates combinational building blocks.
// Sequential wrappers like this are needed until Milestone 2 adds always_ff.
//
// Build with Gowin EDA:
//   1. Add build/blinker.v (generated) and this file to project
//   2. Set this module as top
//   3. Use constraints/tang_nano_9k.cst for pin mapping
//   4. Synthesize, place & route, program

`timescale 1ns / 1ps
`default_nettype none

module blinker_top (
    input  wire sys_clk,      // 27 MHz onboard oscillator
    input  wire sys_rst_n,    // Active-low reset (button S2)
    output wire [5:0] led     // 6 user LEDs (active-low)
);

    // -- Parameters --
    // 27 MHz / 2^24 ~ 1.6 Hz blink rate
    localparam PRESCALE_BITS = 24;
    localparam PRESCALE_MAX  = (1 << PRESCALE_BITS) - 1;

    // -- State registers (sequential - requires always_ff) --
    reg [31:0] counter_reg;
    reg [31:0] prescaler_reg;
    reg        toggle_reg;

    // -- Combinational outputs from ts2v-generated modules --
    wire [31:0] counter_next;
    wire [31:0] prescaler_next;
    wire        prescaler_tick;
    wire        toggle_next;
    wire [31:0] pattern;

    // -- Instantiate ts2v-generated combinational modules --

    blinker_prescaler_next u_prescaler_next (
        .prescaler_value(prescaler_reg),
        .prescaler_max(PRESCALE_MAX),
        .result(prescaler_next)
    );

    blinker_prescaler_tick u_prescaler_tick (
        .prescaler_value(prescaler_reg),
        .prescaler_max(PRESCALE_MAX),
        .result(prescaler_tick)
    );

    blinker_counter_next u_counter_next (
        .current_count(counter_reg),
        .enable(prescaler_tick),
        .result(counter_next)
    );

    blinker_toggle u_toggle (
        .current_state(toggle_reg),
        .enable(prescaler_tick),
        .result(toggle_next)
    );

    blinker_pattern u_pattern (
        .counter_value(counter_reg),
        .pattern_select(32'd0),
        .result(pattern)
    );

    // -- Sequential logic (clock/reset - NOT generated by ts2v Milestone 1) --

    always @(posedge sys_clk or negedge sys_rst_n) begin
        if (!sys_rst_n) begin
            counter_reg   <= 32'd0;
            prescaler_reg <= 32'd0;
            toggle_reg    <= 1'b0;
        end else begin
            counter_reg   <= counter_next;
            prescaler_reg <= prescaler_next;
            toggle_reg    <= toggle_next;
        end
    end

    // -- Output assignment (active-low LEDs on Tang Nano 9K) --
    assign led = ~pattern[5:0];

endmodule

`default_nettype wire
