"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.buildFile = buildFile;
exports.buildClassSource = buildClassSource;
exports.generateConstraints = generateConstraints;
const node_fs_1 = require("node:fs");
const node_path_1 = require("node:path");
const class_module_compiler_1 = require("./class-compiler/class-module-compiler");
const verilog_emitter_1 = require("./codegen/verilog-emitter");
const compiler_error_1 = require("./errors/compiler-error");
const lexer_1 = require("./lexer/lexer");
const parser_1 = require("./parser/parser");
const typechecker_1 = require("./typechecker/typechecker");
function detectMode(source) {
    const hasClass = source.includes('class ');
    const hasHardwareDecorators = source.includes('@Module') ||
        source.includes('@Sequential') ||
        source.includes('@Combinational') ||
        source.includes('extends Module');
    return hasClass && hasHardwareDecorators ? 'class' : 'function';
}
function buildFile(inputPath, outDir) {
    const source = (0, node_fs_1.readFileSync)(inputPath, 'utf-8');
    const baseName = (0, node_path_1.basename)(inputPath, '.ts');
    const mode = detectMode(source);
    if (mode === 'class') {
        const classCompileResult = (0, class_module_compiler_1.compileClassModule)(source);
        if (!classCompileResult.success) {
            return { success: false, outPath: '', lines: 0 };
        }
        const outputPath = (0, node_path_1.join)(outDir, `${baseName}.sv`);
        (0, node_fs_1.writeFileSync)(outputPath, classCompileResult.systemverilog);
        return {
            success: true,
            outPath: outputPath,
            lines: classCompileResult.systemverilog.split('\n').length,
        };
    }
    try {
        const tokens = new lexer_1.Lexer(source).tokenize();
        const ast = new parser_1.Parser(tokens).parse();
        const checkedFunctions = new typechecker_1.TypeChecker().check(ast);
        const verilog = new verilog_emitter_1.VerilogEmitter(checkedFunctions).emit(ast);
        const outputPath = (0, node_path_1.join)(outDir, `${baseName}.sv`);
        (0, node_fs_1.writeFileSync)(outputPath, verilog);
        return { success: true, outPath: outputPath, lines: verilog.split('\n').length };
    }
    catch (error) {
        if (error instanceof compiler_error_1.CompilerError) {
            return { success: false, outPath: '', lines: 0, compilerError: error };
        }
        return { success: false, outPath: '', lines: 0 };
    }
}
// Compile a pre-assembled multi-file source string as one class-mode unit.
// outName is used as the .sv output basename (no extension).
function buildClassSource(source, outName, outDir) {
    const classCompileResult = (0, class_module_compiler_1.compileClassModule)(source);
    if (!classCompileResult.success) {
        return { success: false, outPath: '', lines: 0 };
    }
    const outputPath = (0, node_path_1.join)(outDir, `${outName}.sv`);
    (0, node_fs_1.writeFileSync)(outputPath, classCompileResult.systemverilog);
    return {
        success: true,
        outPath: outputPath,
        lines: classCompileResult.systemverilog.split('\n').length,
    };
}
/** @deprecated Use `generateBoardConstraints` from `packages/core/src/compiler/constraints/generate-board-constraints.ts` instead. */
function generateConstraints(boardJsonPath, outDir) {
    const raw = JSON.parse((0, node_fs_1.readFileSync)(boardJsonPath, 'utf-8'));
    const board = raw.board ?? raw;
    const vendor = String(board.vendor ?? raw.vendor ?? '').toLowerCase();
    const lines = [];
    let extension = '.cst';
    const pins = {};
    const boardPins = board.pins;
    if (boardPins) {
        const ioStandard = String(board.io_standard ?? 'LVCMOS33');
        for (const [name, pin] of Object.entries(boardPins)) {
            const freq = name.includes('clk')
                ? `${String(board.clock_frequency_in_mhz ?? raw.hardware?.clock_frequency_in_mhz ?? 27)}MHz`
                : undefined;
            pins[name] = { pin: String(pin), std: ioStandard, freq };
        }
    }
    const boardClocks = board.clocks;
    if (boardClocks) {
        for (const [name, config] of Object.entries(boardClocks)) {
            pins[name] = { pin: config.pin, std: config.std ?? 'LVCMOS33', freq: config.freq };
        }
    }
    const boardIo = board.io;
    if (boardIo) {
        for (const [name, config] of Object.entries(boardIo)) {
            pins[name] = {
                pin: config.pin,
                std: config.std ?? 'LVCMOS33',
                drive: config.drive,
                pull: config.pull,
            };
        }
    }
    const family = String(board.family ?? board.part ?? 'unknown');
    const part = String(board.part ?? 'unknown');
    if (vendor === 'gowin' || vendor === 'sipeed' || vendor === 'tang') {
        extension = '.cst';
        lines.push(`// Generated by ts2v from ${(0, node_path_1.basename)(boardJsonPath)}`);
        lines.push(`// Target: ${family} (${part})`);
        lines.push('');
        for (const [name, config] of Object.entries(pins)) {
            lines.push(`IO_LOC "${name}" ${config.pin};`);
            let attrs = `IO_TYPE=${config.std}`;
            if (config.drive)
                attrs += ` DRIVE=${config.drive}`;
            if (config.pull)
                attrs += ` PULL_MODE=${config.pull}`;
            lines.push(`IO_PORT "${name}" ${attrs};`);
        }
    }
    else if (vendor === 'xilinx') {
        extension = '.xdc';
        lines.push(`## Generated by ts2v from ${(0, node_path_1.basename)(boardJsonPath)}`);
        lines.push(`## Target: ${family} (${part})`);
        lines.push('');
        for (const [name, config] of Object.entries(pins)) {
            lines.push(`set_property PACKAGE_PIN ${config.pin} [get_ports ${name}]`);
            lines.push(`set_property IOSTANDARD ${config.std} [get_ports ${name}]`);
            if (config.freq) {
                const frequencyMhz = Number.parseFloat(config.freq.replace(/[A-Za-z]/g, ''));
                const period = 1000 / frequencyMhz;
                lines.push(`create_clock -period ${period.toFixed(3)} -name ${name} [get_ports ${name}]`);
            }
        }
    }
    else if (vendor === 'intel' || vendor === 'altera') {
        extension = '.qsf';
        lines.push(`# Generated by ts2v from ${(0, node_path_1.basename)(boardJsonPath)}`);
        lines.push('');
        for (const [name, config] of Object.entries(pins)) {
            lines.push(`set_location_assignment PIN_${config.pin} -to ${name}`);
            lines.push(`set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ${name}`);
        }
    }
    else if (vendor === 'lattice') {
        extension = '.lpf';
        lines.push(`# Generated by ts2v from ${(0, node_path_1.basename)(boardJsonPath)}`);
        lines.push('');
        for (const [name, config] of Object.entries(pins)) {
            lines.push(`LOCATE COMP "${name}" SITE "${config.pin}";`);
            lines.push(`IOBUF PORT "${name}" IO_TYPE=${config.std};`);
            if (config.freq) {
                const frequencyMhz = Number.parseFloat(config.freq.replace(/[A-Za-z]/g, ''));
                lines.push(`FREQUENCY PORT "${name}" ${frequencyMhz} MHz;`);
            }
        }
    }
    const outputPath = (0, node_path_1.join)(outDir, (0, node_path_1.basename)(boardJsonPath).replace('.board.json', extension).replace('.json', extension));
    (0, node_fs_1.writeFileSync)(outputPath, lines.join('\n'));
    return outputPath;
}
//# sourceMappingURL=compiler-engine.js.map