// String constants and error message templates for the compiler.

export const PRODUCT_NAME = 'ts2v';
export const PRODUCT_VERSION = '1.0.0';
export const PRODUCT_DESCRIPTION = 'TypeScript to Verilog transpiler';

// Verilog output header
export const VERILOG_HEADER = '// Generated by ts2v - TypeScript to Verilog transpiler';
export const VERILOG_TIMESCALE = '`timescale 1ns / 1ps';
export const VERILOG_DEFAULT_NETTYPE_NONE = '`default_nettype none';
export const VERILOG_DEFAULT_NETTYPE_WIRE = '`default_nettype wire';

// Error message templates (use %s for interpolation)
export const ERROR_UNEXPECTED_TOKEN = 'Unexpected token "%s" at line %d, column %d';
export const ERROR_EXPECTED_TOKEN = 'Expected "%s" but found "%s" at line %d, column %d';
export const ERROR_UNKNOWN_TYPE = 'Unknown type "%s" at line %d, column %d';
export const ERROR_TYPE_MISMATCH = 'Type mismatch: cannot assign "%s" to "%s" at line %d, column %d';
export const ERROR_UNDECLARED_VARIABLE = 'Undeclared variable "%s" at line %d, column %d';
export const ERROR_DUPLICATE_DECLARATION = 'Duplicate declaration "%s" at line %d, column %d';
export const ERROR_UNSUPPORTED_CONSTRUCT = 'Unsupported construct "%s" at line %d, column %d';
export const ERROR_BIT_WIDTH_MISMATCH = 'Bit-width mismatch: %d-bit value assigned to %d-bit target at line %d, column %d';
export const ERROR_EMPTY_SOURCE = 'Source file is empty';
export const ERROR_UNTERMINATED_STRING = 'Unterminated string literal at line %d, column %d';
export const ERROR_INVALID_NUMBER = 'Invalid numeric literal "%s" at line %d, column %d';
export const ERROR_MISSING_RETURN = 'Function "%s" must have a return statement';
export const ERROR_CONST_REASSIGN = 'Cannot reassign const variable "%s" at line %d, column %d';
export const ERROR_ARRAY_SIZE_REQUIRED = 'Fixed array size required for hardware synthesis at line %d, column %d';
