// Board Constraint Generator (Spec §62)
// Reads board.json → outputs vendor-specific constraint files
// Supports: Gowin (.cst), Xilinx/Vivado (.xdc), Intel/Quartus (.qsf), Lattice (.lpf)

export interface BoardDefinition {
  vendor: 'gowin' | 'xilinx' | 'intel' | 'lattice';
  family: string;
  part: string;
  // Clock ports keyed by logical top-port name.
  // `pin`: package pin number as string, `freq`: input frequency, `std`: IO standard.
  clocks: Record<string, { pin: string; freq: string; std: string }>;
  // Generic IO ports keyed by logical top-port name.
  // `std` maps to vendor IO standard field.
  // `drive` and `pull` are optional and only emitted for vendors that support them in this generator.
  io: Record<string, { pin: string; std: string; drive?: string; pull?: string }>;
}

export interface ConstraintOutput {
  filename: string;
  content: string;
}

export function generateConstraints(board: BoardDefinition): ConstraintOutput {
  switch (board.vendor) {
    case 'gowin':
      return generateGowin(board);
    case 'xilinx':
      return generateXilinx(board);
    case 'intel':
      return generateQuartus(board);
    case 'lattice':
      return generateLattice(board);
    default:
      throw new Error(`Unsupported vendor: ${board.vendor}`);
  }
}

function freqToMHz(freq: string): number {
  const match = freq.match(/^(\d+(?:\.\d+)?)\s*(MHz|KHz|Hz)?$/i);
  if (!match) throw new Error(`Invalid frequency: ${freq}`);
  const val = parseFloat(match[1]);
  const unit = (match[2] || 'MHz').toLowerCase();
  if (unit === 'mhz') return val;
  if (unit === 'khz') return val / 1000;
  if (unit === 'hz') return val / 1_000_000;
  return val;
}

function freqToPeriod(freq: string): string {
  const mhz = freqToMHz(freq);
  return (1000 / mhz).toFixed(3);
}

// ============================================================
// Gowin EDA (.cst)
// ============================================================
function generateGowin(board: BoardDefinition): ConstraintOutput {
  const lines: string[] = [
    `// Gowin Physical Constraints File`,
    `// Generated by ts2v constraint generator`,
    `// Board: ${board.family} (${board.part})`,
    ``,
  ];

  for (const [name, def] of Object.entries(board.clocks)) {
    lines.push(`IO_LOC  "${name}" ${def.pin};`);
    lines.push(`IO_PORT "${name}" IO_TYPE=${def.std};`);
    lines.push(``);
  }

  for (const [name, def] of Object.entries(board.io)) {
    const svName = name.replace(/\[(\d+)\]/, '[$1]');
    lines.push(`IO_LOC  "${svName}" ${def.pin};`);
    let attrs = `IO_TYPE=${def.std}`;
    if (def.drive) attrs += ` DRIVE=${def.drive}`;
    if (def.pull) attrs += ` PULL_MODE=${def.pull}`;
    lines.push(`IO_PORT "${svName}" ${attrs};`);
  }

  return { filename: `${board.family}.cst`, content: lines.join('\n') };
}

// ============================================================
// Xilinx Vivado (.xdc)
// ============================================================
function generateXilinx(board: BoardDefinition): ConstraintOutput {
  const lines: string[] = [
    `# Xilinx Design Constraints File`,
    `# Generated by ts2v constraint generator`,
    `# Board: ${board.family} (${board.part})`,
    ``,
  ];

  for (const [name, def] of Object.entries(board.clocks)) {
    const period = freqToPeriod(def.freq);
    const half = (parseFloat(period) / 2).toFixed(3);
    lines.push(`set_property PACKAGE_PIN ${def.pin} [get_ports ${name}]`);
    lines.push(`set_property IOSTANDARD ${def.std} [get_ports ${name}]`);
    lines.push(`create_clock -period ${period} -name ${name} -waveform {0.000 ${half}} [get_ports ${name}]`);
    lines.push(``);
  }

  for (const [name, def] of Object.entries(board.io)) {
    lines.push(`set_property PACKAGE_PIN ${def.pin} [get_ports ${name}]`);
    lines.push(`set_property IOSTANDARD ${def.std} [get_ports ${name}]`);
    if (def.drive) lines.push(`set_property DRIVE ${def.drive} [get_ports ${name}]`);
    if (def.pull) lines.push(`set_property PULLTYPE ${def.pull} [get_ports ${name}]`);
  }

  return { filename: `${board.family}.xdc`, content: lines.join('\n') };
}

// ============================================================
// Intel Quartus (.qsf)
// ============================================================
function generateQuartus(board: BoardDefinition): ConstraintOutput {
  const lines: string[] = [
    `# Intel Quartus Settings File`,
    `# Generated by ts2v constraint generator`,
    `# Board: ${board.family} (${board.part})`,
    ``,
    `set_global_assignment -name DEVICE ${board.part}`,
    ``,
  ];

  for (const [name, def] of Object.entries(board.clocks)) {
    lines.push(`set_location_assignment PIN_${def.pin} -to ${name}`);
    lines.push(`set_instance_assignment -name IO_STANDARD "${def.std}" -to ${name}`);
    lines.push(``);
  }

  for (const [name, def] of Object.entries(board.io)) {
    lines.push(`set_location_assignment PIN_${def.pin} -to ${name}`);
    lines.push(`set_instance_assignment -name IO_STANDARD "${def.std}" -to ${name}`);
  }

  return { filename: `${board.family}.qsf`, content: lines.join('\n') };
}

// ============================================================
// Lattice (.lpf)
// ============================================================
function generateLattice(board: BoardDefinition): ConstraintOutput {
  const lines: string[] = [
    `# Lattice Physical Preferences File`,
    `# Generated by ts2v constraint generator`,
    `# Board: ${board.family} (${board.part})`,
    ``,
  ];

  for (const [name, def] of Object.entries(board.clocks)) {
    const period = freqToPeriod(def.freq);
    lines.push(`LOCATE COMP "${name}" SITE "${def.pin}";`);
    lines.push(`IOBUF PORT "${name}" IO_TYPE=${def.std};`);
    lines.push(`FREQUENCY PORT "${name}" ${freqToMHz(def.freq)} MHz;`);
    lines.push(``);
  }

  for (const [name, def] of Object.entries(board.io)) {
    lines.push(`LOCATE COMP "${name}" SITE "${def.pin}";`);
    lines.push(`IOBUF PORT "${name}" IO_TYPE=${def.std};`);
  }

  return { filename: `${board.family}.lpf`, content: lines.join('\n') };
}
