import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { type BoardDefinition, generateConstraints } from './board-constraint-gen';

export type { BoardDefinition };

export function generateBoardConstraints(board: BoardDefinition, outDir: string): string {
  const { filename, content } = generateConstraints(board);
  const outputPath = join(outDir, filename);
  writeFileSync(outputPath, content);
  return outputPath;
}

export interface ClockDomainSpec {
  name: string;
  freq?: number;
  pin?: string;
}

export function generateClockConstraints(clocks: ClockDomainSpec[], outPath: string): void {
  const lines: string[] = [
    '# Clock constraints generated by ts2v from @ClockDomain declarations',
    '# Format: nextpnr-compatible SDC',
    '',
  ];
  for (const clk of clocks) {
    if (clk.freq) {
      const periodNs = (1_000_000_000 / clk.freq).toFixed(3);
      if (clk.pin) {
        lines.push(`create_clock -period ${periodNs} -name ${clk.name} [get_ports ${clk.pin}]`);
      } else {
        lines.push(`create_clock -period ${periodNs} -name ${clk.name}`);
      }
    }
  }
  writeFileSync(outPath, lines.join('\n') + '\n');
}
