// Structural module emitter: port lists, internal signals, submodule instances,
// enums, SVA assertions, and top-level module scaffold.

import {
    ClassModuleAST, EnumAST, SubmoduleAST, ModuleSignature,
} from './class-module-ast';
import { sanitize, formatWidth, enumBits } from './class-sv-helpers';
import { SequentialEmitter } from './class-sequential-emitter';
import { codegenError } from '../errors/compiler-error';
import { STDLIB_CDC_PRIMITIVES, CDC_PRIMITIVE_TYPES } from './stdlib-sv-templates';

export class ClassModuleEmitter extends SequentialEmitter {
    private module_signatures: Map<string, ModuleSignature> = new Map();
    private emitted_stdlib: Set<string> = new Set();

    emit(parsed: { enums: EnumAST[]; modules: ClassModuleAST[]; consts?: readonly { name: string; value: string }[] }): string {
        // Populate const map for inline substitution in expressions.
        if (parsed.consts) {
            for (const c of parsed.consts) {
                this.global_consts.set(c.name, c.value);
            }
        }
        this.lines = [];
        this.emitted_stdlib = new Set();
        this.line('// Generated by ts2v v2.0.0 - IEEE 1800-2017 Compliant SystemVerilog');
        this.line('`timescale 1ns / 1ps');
        this.line('`default_nettype none');
        this.line('');

        // Pre-register stdlib CDC primitive signatures.
        for (const [typeName, template] of Object.entries(STDLIB_CDC_PRIMITIVES)) {
            if (!this.module_signatures.has(typeName)) {
                this.module_signatures.set(typeName, {
                    name: typeName,
                    inputs: template.signature.inputs,
                    outputs: template.signature.outputs,
                    parameters: template.signature.parameters,
                });
            }
        }

        for (const mod of parsed.modules) {
            this.registerModuleSignature(mod);
        }

        for (const e of parsed.enums) {
            this.emitEnum(e);
            this.line('');
        }

        // Emit stdlib CDC primitive SV definitions before user modules.
        for (const mod of parsed.modules) {
            for (const sub of mod.submodules) {
                if (CDC_PRIMITIVE_TYPES.has(sub.module_type) && !this.emitted_stdlib.has(sub.module_type)) {
                    this.emitted_stdlib.add(sub.module_type);
                    const template = STDLIB_CDC_PRIMITIVES[sub.module_type];
                    for (const svLine of template.sv.split('\n')) {
                        this.line(svLine);
                    }
                    this.line('');
                }
            }
        }

        for (const mod of parsed.modules) {
            this.checkCdcCrossings(mod);
            this.emitModule(mod, parsed.enums);
            this.line('');
        }

        this.line('`default_nettype wire');
        return this.lines.join('\n');
    }

    private checkCdcCrossings(mod: ClassModuleAST): void {
        const seqMethods = mod.methods.filter(m => m.type === 'sequential');
        const uniqueClocks = new Set(seqMethods.map(m => m.clock));
        if (uniqueClocks.size <= 1) return;

        // Collect signals ASSIGNED per clock domain.
        const assignedByClk = new Map<string, Set<string>>();
        // Collect signals READ per clock domain.
        const readByClk = new Map<string, Set<string>>();
        for (const m of seqMethods) {
            if (!assignedByClk.has(m.clock)) assignedByClk.set(m.clock, new Set());
            if (!readByClk.has(m.clock)) readByClk.set(m.clock, new Set());
            this.collectAssignedSignals(m.body, assignedByClk.get(m.clock)!);
            this.collectReadSignals(m.body, readByClk.get(m.clock)!);
        }

        // Check if CDC submodules exist (suppress warnings for guarded crossings).
        const hasCdcPrimitive = mod.submodules.some(s => CDC_PRIMITIVE_TYPES.has(s.module_type));

        if (!hasCdcPrimitive) {
            // Warn if a signal is ASSIGNED in domain A and READ in domain B.
            const clocks = Array.from(uniqueClocks);
            const warned = new Set<string>();
            for (let i = 0; i < clocks.length; i++) {
                for (let j = 0; j < clocks.length; j++) {
                    if (i === j) continue;
                    const clkA = clocks[i];
                    const clkB = clocks[j];
                    const assignedInA = assignedByClk.get(clkA) ?? new Set<string>();
                    const readInB = readByClk.get(clkB) ?? new Set<string>();
                    for (const sig of assignedInA) {
                        const key = `${sig}:${clkA}->${clkB}`;
                        if (readInB.has(sig) && !warned.has(key)) {
                            warned.add(key);
                            console.warn(
                                `[ts2v CDC warning] Module '${mod.name}': signal '${sig}' assigned in domain clocked by '${clkA}' is read in domain clocked by '${clkB}' without a recognized CDC primitive (ClockDomainCrossing or AsyncFifo).`
                            );
                        }
                    }
                }
            }
        }
    }

    private collectAssignedSignals(stmts: import('./class-module-ast').StatementAST[], out: Set<string>): void {
        for (const stmt of stmts) {
            if (stmt.kind === 'assign') {
                out.add(stmt.target.replace(/^this\./, '').replace(/\[.*\]$/, ''));
            } else if (stmt.kind === 'if') {
                this.collectAssignedSignals(stmt.then_body, out);
                if (stmt.else_body) this.collectAssignedSignals(stmt.else_body, out);
            } else if (stmt.kind === 'switch') {
                for (const c of stmt.cases) this.collectAssignedSignals(c.body, out);
                if (stmt.default_body) this.collectAssignedSignals(stmt.default_body, out);
            }
        }
    }

    private collectReadSignals(stmts: import('./class-module-ast').StatementAST[], out: Set<string>): void {
        const extractRefs = (expr: string): void => {
            for (const m of expr.matchAll(/this\.(\w+)/g)) {
                out.add(m[1]);
            }
        };
        for (const stmt of stmts) {
            if (stmt.kind === 'assign') {
                extractRefs(stmt.value);
            } else if (stmt.kind === 'if') {
                extractRefs(stmt.condition);
                this.collectReadSignals(stmt.then_body, out);
                if (stmt.else_body) this.collectReadSignals(stmt.else_body, out);
            } else if (stmt.kind === 'switch') {
                extractRefs(stmt.expr);
                for (const c of stmt.cases) this.collectReadSignals(c.body, out);
                if (stmt.default_body) this.collectReadSignals(stmt.default_body, out);
            }
        }
    }

    registerModuleSignature(mod: ClassModuleAST): void {
        const has_seq = mod.methods.some(m => m.type === 'sequential');
        const inputs: { name: string; bit_width: number }[] = [];
        const outputs: { name: string; bit_width: number }[] = [];
        for (const p of mod.properties) {
            if (p.direction === 'input') inputs.push({ name: p.name, bit_width: p.bit_width });
            if (p.direction === 'output') outputs.push({ name: p.name, bit_width: p.bit_width });
        }
        if (has_seq) {
            // Register all unique clock signals from sequential methods.
            const seqClocks = new Set<string>();
            for (const m of mod.methods) {
                if (m.type === 'sequential') seqClocks.add(m.clock);
            }
            for (const clk of seqClocks) {
                if (!inputs.some(i => i.name === clk)) {
                    inputs.unshift({ name: clk, bit_width: 1 });
                }
            }
            if (mod.config.reset_type === 'async' && mod.config.reset_signal !== 'no_rst') {
                if (!inputs.some(i => i.name === mod.config.reset_signal)) {
                    inputs.push({ name: mod.config.reset_signal, bit_width: 1 });
                }
            }
        }
        this.module_signatures.set(mod.name, { name: mod.name, inputs, outputs, parameters: mod.parameters ?? [] });
    }

    private emitEnum(e: EnumAST): void {
        const bits = enumBits(e.members.length);
        this.line(`typedef enum logic ${formatWidth(bits)} {`);
        this.indent++;
        for (let i = 0; i < e.members.length; i++) {
            const m = e.members[i];
            const comma = i < e.members.length - 1 ? ',' : '';
            this.line(`${m.name} = ${bits}'d${m.value}${comma}`);
        }
        this.indent--;
        this.line(`} ${e.name};`);
    }

    private emitModule(mod: ClassModuleAST, global_enums: EnumAST[]): void {
        const all_enums = [...global_enums, ...mod.enums];
        const has_sequential = mod.methods.some(m => m.type === 'sequential');
        const has_declared_reset =
            mod.properties.some(p => p.direction === 'input' && p.name === mod.config.reset_signal) ||
            (mod.config.reset_type === 'async' && mod.config.reset_signal !== 'no_rst');

        const pw = new Map<string, number>();
        for (const p of mod.properties) pw.set(p.name, p.bit_width);

        if (mod.parameters.length > 0) {
            this.line(`module ${mod.name} #(`);
            this.indent++;
            for (let i = 0; i < mod.parameters.length; i++) {
                const param = mod.parameters[i];
                const comma = i < mod.parameters.length - 1 ? ',' : '';
                this.line(`parameter logic [${param.bit_width - 1}:0] ${sanitize(param.name)} = ${param.default_value}${comma}`);
            }
            this.indent--;
            this.line(`) (`);
        } else {
            this.line(`module ${mod.name} (`);
        }
        this.indent++;
        const ports: string[] = [];

        if (has_sequential) {
            // Collect unique clock signals across all sequential methods.
            const seqClocks = new Set<string>();
            for (const m of mod.methods) {
                if (m.type === 'sequential') seqClocks.add(m.clock);
            }
            for (const clk of seqClocks) {
                if (!mod.properties.find(p => p.name === clk)) {
                    ports.push(`input  logic ${sanitize(clk)}`);
                }
            }
            if (has_declared_reset && !mod.properties.find(p => p.name === mod.config.reset_signal)) {
                ports.push(`input  logic ${sanitize(mod.config.reset_signal)}`);
            }
        }

        for (const p of mod.properties) {
            if (p.direction === 'input') {
                ports.push(`input  logic ${formatWidth(p.bit_width)} ${sanitize(p.name)}`);
            } else if (p.direction === 'output') {
                ports.push(`output      logic ${formatWidth(p.bit_width)} ${sanitize(p.name)}`);
            }
        }

        for (let i = 0; i < ports.length; i++) {
            this.line(`${ports[i]}${i < ports.length - 1 ? ',' : ''}`);
        }
        this.indent--;
        this.line(');');
        this.line('');

        const internals = mod.properties.filter(p => p.direction === 'internal');
        if (internals.length > 0) {
            this.line('    // Internal signals');
            for (const p of internals) {
                const w = formatWidth(p.bit_width);
                const n = sanitize(p.name);
                if (p.is_const) {
                    this.line(`    localparam ${w ? 'logic ' + w : ''} ${n} = ${this.translateExpr(p.initial_value || '0', all_enums, mod)};`);
                } else if (p.is_array) {
                    if (p.array_size <= 0) {
                        throw codegenError(
                            `Fixed array size required for hardware synthesis: '${p.name}' declared as array but array_size is 0. Use LogicArray<W, SIZE> with both generic arguments.`,
                            { line: 0, column: 0 }
                        );
                    }
                    this.line(`    logic [${p.bit_width - 1}:0] ${n} [0:${p.array_size - 1}];`);
                } else {
                    this.line(`    logic ${w} ${n};`);
                }
            }
            this.line('');
        }

        if (mod.submodules.length > 0) {
            this.line('    // Submodule instances');
            for (const sub of mod.submodules) {
                this.emitSubmoduleInst(sub, mod);
            }
            this.line('');
        }

        for (const method of mod.methods) {
            if (method.type === 'sequential') {
                this.emitSequential(method, mod, all_enums, pw);
            } else {
                this.emitCombinational(method, mod, all_enums, pw);
            }
            this.line('');
        }

        if (mod.assertions.length > 0) {
            this.line('    // SystemVerilog Assertions (IEEE 1800-2017 SVA)');
            const clk = mod.methods.find(m => m.type === 'sequential')?.clock || 'clk';
            for (const a of mod.assertions) {
                const cond = this.translateExpr(a.condition, all_enums, mod);
                const label = a.label || `assert_${mod.assertions.indexOf(a)}`;
                if (a.message) {
                    this.line(`    ${label}: assert property (@(posedge ${clk}) ${cond})`);
                    this.line(`        else $error("${a.message}");`);
                } else {
                    this.line(`    ${label}: assert property (@(posedge ${clk}) ${cond});`);
                }
            }
            this.line('');
        }

        this.line('endmodule');
    }

    private emitSubmoduleInst(sub: SubmoduleAST, parent: ClassModuleAST): void {
        const sig = this.module_signatures.get(sub.module_type);
        const inst = sanitize(sub.instance_name);

        if (sub.port_map.length > 0 || sub.param_map.length > 0) {
            if (sub.param_map.length > 0) {
                this.line(`    ${sub.module_type} #(`);
                for (let i = 0; i < sub.param_map.length; i++) {
                    const p = sub.param_map[i];
                    const comma = i < sub.param_map.length - 1 ? ',' : '';
                    this.line(`        .${sanitize(p.param_name)}(${p.value})${comma}`);
                }
                this.line(`    ) ${inst} (`);
            } else {
                this.line(`    ${sub.module_type} ${inst} (`);
            }
            const bindings = sub.port_map.map(b => `.${sanitize(b.port_name)}(${sanitize(b.wire_name)})`);
            for (let i = 0; i < bindings.length; i++) {
                this.line(`        ${bindings[i]}${i < bindings.length - 1 ? ',' : ''}`);
            }
            this.line('    );');
            return;
        }

        if (sig) {
            const bindings: string[] = [];
            // Derive clock name from sequential method or from an explicit @Input clk port.
            // This allows pure wiring modules (no @Sequential) to still propagate clk.
            const seq_clk = parent.methods.find(m => m.type === 'sequential')?.clock;
            const input_clk = parent.properties.find(p => p.direction === 'input' && (p.name === 'clk' || p.name === seq_clk))?.name;
            const parent_clk = seq_clk ?? input_clk;
            const parent_rst = parent.config.reset_signal;
            if (parent_clk) {
                const child_needs_clk = sig.inputs.some(i => i.name === parent_clk || i.name === 'clk');
                if (child_needs_clk) bindings.push(`.${sanitize(parent_clk)}(${sanitize(parent_clk)})`);
                const child_needs_rst = sig.inputs.some(i => i.name === parent_rst);
                if (child_needs_rst) bindings.push(`.${sanitize(parent_rst)}(${sanitize(parent_rst)})`);
            }
            for (const inp of sig.inputs) {
                if (inp.name === parent_clk || inp.name === parent_rst || inp.name === 'clk' || inp.name === parent.config.reset_signal) continue;
                const has = parent.properties.find(p => p.name === inp.name);
                bindings.push(`.${sanitize(inp.name)}(${has ? sanitize(inp.name) : '/* unconnected */'})`);
            }
            for (const outp of sig.outputs) {
                const has = parent.properties.find(p => p.name === outp.name);
                bindings.push(`.${sanitize(outp.name)}(${has ? sanitize(outp.name) : '/* unconnected */'})`);
            }
            this.line(`    ${sub.module_type} ${inst} (`);
            for (let i = 0; i < bindings.length; i++) {
                this.line(`        ${bindings[i]}${i < bindings.length - 1 ? ',' : ''}`);
            }
            this.line('    );');
            return;
        }

        this.line(`    // WARNING: Unknown module type '${sub.module_type}' for '${sub.instance_name}'`);
        this.line(`    // ${sub.module_type} ${inst} ( /* unresolved */ );`);
    }
}
