// Structural module emitter: port lists, internal signals, submodule instances,
// enums, SVA assertions, and top-level module scaffold.

import {
    ClassModuleAST, EnumAST, SubmoduleAST, ModuleSignature,
} from './class-module-ast';
import { sanitize, formatWidth, enumBits } from './class-sv-helpers';
import { SequentialEmitter } from './class-sequential-emitter';

export class ClassModuleEmitter extends SequentialEmitter {
    private module_signatures: Map<string, ModuleSignature> = new Map();

    emit(parsed: { enums: EnumAST[]; modules: ClassModuleAST[]; consts?: readonly { name: string; value: string }[] }): string {
        // Populate const map for inline substitution in expressions.
        if (parsed.consts) {
            for (const c of parsed.consts) {
                this.global_consts.set(c.name, c.value);
            }
        }
        this.lines = [];
        this.line('// Generated by ts2v v2.0.0 - IEEE 1800-2017 Compliant SystemVerilog');
        this.line('`timescale 1ns / 1ps');
        this.line('`default_nettype none');
        this.line('');

        for (const mod of parsed.modules) {
            this.registerModuleSignature(mod);
        }

        for (const e of parsed.enums) {
            this.emitEnum(e);
            this.line('');
        }

        for (const mod of parsed.modules) {
            this.emitModule(mod, parsed.enums);
            this.line('');
        }

        this.line('`default_nettype wire');
        return this.lines.join('\n');
    }

    registerModuleSignature(mod: ClassModuleAST): void {
        const has_seq = mod.methods.some(m => m.type === 'sequential');
        const inputs: { name: string; bit_width: number }[] = [];
        const outputs: { name: string; bit_width: number }[] = [];
        for (const p of mod.properties) {
            if (p.direction === 'input') inputs.push({ name: p.name, bit_width: p.bit_width });
            if (p.direction === 'output') outputs.push({ name: p.name, bit_width: p.bit_width });
        }
        if (has_seq && mod.config.reset_type === 'async' && mod.config.reset_signal !== 'no_rst') {
            if (!inputs.some(i => i.name === mod.config.reset_signal)) {
                inputs.push({ name: mod.config.reset_signal, bit_width: 1 });
            }
        }
        this.module_signatures.set(mod.name, { name: mod.name, inputs, outputs });
    }

    private emitEnum(e: EnumAST): void {
        const bits = enumBits(e.members.length);
        this.line(`typedef enum logic ${formatWidth(bits)} {`);
        this.indent++;
        for (let i = 0; i < e.members.length; i++) {
            const m = e.members[i];
            const comma = i < e.members.length - 1 ? ',' : '';
            this.line(`${m.name} = ${bits}'d${m.value}${comma}`);
        }
        this.indent--;
        this.line(`} ${e.name};`);
    }

    private emitModule(mod: ClassModuleAST, global_enums: EnumAST[]): void {
        const all_enums = [...global_enums, ...mod.enums];
        const has_sequential = mod.methods.some(m => m.type === 'sequential');
        const has_declared_reset =
            mod.properties.some(p => p.direction === 'input' && p.name === mod.config.reset_signal) ||
            (mod.config.reset_type === 'async' && mod.config.reset_signal !== 'no_rst');

        const pw = new Map<string, number>();
        for (const p of mod.properties) pw.set(p.name, p.bit_width);

        this.line(`module ${mod.name} (`);
        this.indent++;
        const ports: string[] = [];

        if (has_sequential) {
            const clk = mod.methods.find(m => m.type === 'sequential')!.clock;
            if (!mod.properties.find(p => p.name === clk)) {
                ports.push(`input  logic ${sanitize(clk)}`);
            }
            if (has_declared_reset && !mod.properties.find(p => p.name === mod.config.reset_signal)) {
                ports.push(`input  logic ${sanitize(mod.config.reset_signal)}`);
            }
        }

        for (const p of mod.properties) {
            if (p.direction === 'input') {
                ports.push(`input  logic ${formatWidth(p.bit_width)} ${sanitize(p.name)}`);
            } else if (p.direction === 'output') {
                ports.push(`output      logic ${formatWidth(p.bit_width)} ${sanitize(p.name)}`);
            }
        }

        for (let i = 0; i < ports.length; i++) {
            this.line(`${ports[i]}${i < ports.length - 1 ? ',' : ''}`);
        }
        this.indent--;
        this.line(');');
        this.line('');

        const internals = mod.properties.filter(p => p.direction === 'internal');
        if (internals.length > 0) {
            this.line('    // Internal signals');
            for (const p of internals) {
                const w = formatWidth(p.bit_width);
                const n = sanitize(p.name);
                if (p.is_const) {
                    this.line(`    localparam ${w ? 'logic ' + w : ''} ${n} = ${this.translateExpr(p.initial_value || '0', all_enums, mod)};`);
                } else if (p.is_array && p.array_size > 0) {
                    this.line(`    logic ${w} ${n} [0:${p.array_size - 1}];`);
                } else {
                    this.line(`    logic ${w} ${n};`);
                }
            }
            this.line('');
        }

        if (mod.submodules.length > 0) {
            this.line('    // Submodule instances');
            for (const sub of mod.submodules) {
                this.emitSubmoduleInst(sub, mod);
            }
            this.line('');
        }

        for (const method of mod.methods) {
            if (method.type === 'sequential') {
                this.emitSequential(method, mod, all_enums, pw);
            } else {
                this.emitCombinational(method, mod, all_enums, pw);
            }
            this.line('');
        }

        if (mod.assertions.length > 0) {
            this.line('    // SystemVerilog Assertions (IEEE 1800-2017 SVA)');
            const clk = mod.methods.find(m => m.type === 'sequential')?.clock || 'clk';
            for (const a of mod.assertions) {
                const cond = this.translateExpr(a.condition, all_enums, mod);
                const label = a.label || `assert_${mod.assertions.indexOf(a)}`;
                if (a.message) {
                    this.line(`    ${label}: assert property (@(posedge ${clk}) ${cond})`);
                    this.line(`        else $error("${a.message}");`);
                } else {
                    this.line(`    ${label}: assert property (@(posedge ${clk}) ${cond});`);
                }
            }
            this.line('');
        }

        this.line('endmodule');
    }

    private emitSubmoduleInst(sub: SubmoduleAST, parent: ClassModuleAST): void {
        const sig = this.module_signatures.get(sub.module_type);
        const inst = sanitize(sub.instance_name);

        if (sub.port_map.length > 0) {
            const bindings = sub.port_map.map(b => `.${sanitize(b.port_name)}(${sanitize(b.wire_name)})`);
            this.line(`    ${sub.module_type} ${inst} (`);
            for (let i = 0; i < bindings.length; i++) {
                this.line(`        ${bindings[i]}${i < bindings.length - 1 ? ',' : ''}`);
            }
            this.line('    );');
            return;
        }

        if (sig) {
            const bindings: string[] = [];
            const parent_clk = parent.methods.find(m => m.type === 'sequential')?.clock;
            const parent_rst = parent.config.reset_signal;
            if (parent_clk) {
                const child_needs_clk = sig.inputs.some(i => i.name === parent_clk || i.name === 'clk');
                if (child_needs_clk) bindings.push(`.${sanitize(parent_clk)}(${sanitize(parent_clk)})`);
                const child_needs_rst = sig.inputs.some(i => i.name === parent_rst);
                if (child_needs_rst) bindings.push(`.${sanitize(parent_rst)}(${sanitize(parent_rst)})`);
            }
            for (const inp of sig.inputs) {
                if (inp.name === parent_clk || inp.name === parent_rst || inp.name === 'clk' || inp.name === parent.config.reset_signal) continue;
                const has = parent.properties.find(p => p.name === inp.name);
                bindings.push(`.${sanitize(inp.name)}(${has ? sanitize(inp.name) : '/* unconnected */'})`);
            }
            for (const outp of sig.outputs) {
                const has = parent.properties.find(p => p.name === outp.name);
                bindings.push(`.${sanitize(outp.name)}(${has ? sanitize(outp.name) : '/* unconnected */'})`);
            }
            this.line(`    ${sub.module_type} ${inst} (`);
            for (let i = 0; i < bindings.length; i++) {
                this.line(`        ${bindings[i]}${i < bindings.length - 1 ? ',' : ''}`);
            }
            this.line('    );');
            return;
        }

        this.line(`    // WARNING: Unknown module type '${sub.module_type}' for '${sub.instance_name}'`);
        this.line(`    // ${sub.module_type} ${inst} ( /* unresolved */ );`);
    }
}
