#!/usr/bin/env node
// ts2v CLI: TypeScript to SystemVerilog compiler
// Usage: ts2v build <file.ts|dir> [--out <dir>] [--board <board.json>]

import * as fs from 'fs';
import * as path from 'path';
import { compileClassModule } from './class-compiler/class-module-compiler';
import { Lexer } from './lexer/lexer';
import { Parser } from './parser/parser';
import { TypeChecker } from './typechecker/typechecker';
import { VerilogEmitter } from './codegen/verilog-emitter';

interface BuildOptions {
  input: string;
  outDir: string;
  board?: string;
}

function parseArgs(args: string[]): BuildOptions {
  const opts: BuildOptions = { input: '', outDir: './build' };
  let i = 0;
  while (i < args.length) {
    if (args[i] === '--out' && i + 1 < args.length) { opts.outDir = args[++i]; }
    else if (args[i] === '--board' && i + 1 < args.length) { opts.board = args[++i]; }
    else if (!args[i].startsWith('-')) { opts.input = args[i]; }
    i++;
  }
  return opts;
}

export function generateConstraints(boardJson: string, outDir: string): string {
  const raw = JSON.parse(fs.readFileSync(boardJson, 'utf-8'));
  // Support both flat format and nested board.* format
  const board = raw.board || raw;
  const vendor = (board.vendor || raw.vendor || '').toLowerCase();
  let lines: string[] = [];
  let ext = '.cst';

  // Normalize pins: board.pins, board.clocks + board.io
  const pins: Record<string, { pin: string; std: string; freq?: string }> = {};
  if (board.pins) {
    const io_std = board.io_standard || 'LVCMOS33';
    for (const [name, pin] of Object.entries(board.pins)) {
      const freq = name.includes('clk') ? `${board.clock_frequency_in_mhz || raw.hardware?.clock_frequency_in_mhz || 27}MHz` : undefined;
      pins[name] = { pin: String(pin), std: io_std, freq };
    }
  }
  if (board.clocks) {
    for (const [name, cfg] of Object.entries(board.clocks) as any) {
      pins[name] = { pin: cfg.pin, std: cfg.std || 'LVCMOS33', freq: cfg.freq };
    }
  }
  if (board.io) {
    for (const [name, cfg] of Object.entries(board.io) as any) {
      pins[name] = { pin: cfg.pin, std: cfg.std || 'LVCMOS33' };
    }
  }

  const family = board.family || board.part || 'unknown';
  const part = board.part || 'unknown';

  if (vendor === 'gowin' || vendor === 'sipeed' || vendor === 'tang') {
    ext = '.cst';
    lines.push(`// Generated by ts2v from ${path.basename(boardJson)}`);
    lines.push(`// Target: ${family} (${part})`);
    lines.push('');
    for (const [name, cfg] of Object.entries(pins)) {
      lines.push(`IO_LOC "${name}" ${cfg.pin};`);
      lines.push(`IO_PORT "${name}" IO_TYPE=${cfg.std};`);
    }
  } else if (vendor === 'xilinx') {
    ext = '.xdc';
    lines.push(`## Generated by ts2v from ${path.basename(boardJson)}`);
    lines.push(`## Target: ${family} (${part})`);
    lines.push('');
    for (const [name, cfg] of Object.entries(pins)) {
      lines.push(`set_property PACKAGE_PIN ${cfg.pin} [get_ports ${name}]`);
      lines.push(`set_property IOSTANDARD ${cfg.std} [get_ports ${name}]`);
      if (cfg.freq) {
        const freq_mhz = parseFloat(cfg.freq.replace(/[A-Za-z]/g, ''));
        const period = 1000 / freq_mhz;
        lines.push(`create_clock -period ${period.toFixed(3)} -name ${name} [get_ports ${name}]`);
      }
    }
  } else if (vendor === 'intel' || vendor === 'altera') {
    ext = '.qsf';
    lines.push(`# Generated by ts2v from ${path.basename(boardJson)}`);
    lines.push('');
    for (const [name, cfg] of Object.entries(pins)) {
      lines.push(`set_location_assignment PIN_${cfg.pin} -to ${name}`);
      lines.push(`set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ${name}`);
    }
  } else if (vendor === 'lattice') {
    ext = '.lpf';
    lines.push(`# Generated by ts2v from ${path.basename(boardJson)}`);
    lines.push('');
    for (const [name, cfg] of Object.entries(pins)) {
      lines.push(`LOCATE COMP "${name}" SITE "${cfg.pin}";`);
      lines.push(`IOBUF PORT "${name}" IO_TYPE=${cfg.std};`);
      if (cfg.freq) {
        const freq_mhz = parseFloat(cfg.freq.replace(/[A-Za-z]/g, ''));
        lines.push(`FREQUENCY PORT "${name}" ${freq_mhz} MHz;`);
      }
    }
  }

  const outPath = path.join(outDir, path.basename(boardJson).replace('.board.json', ext).replace('.json', ext));
  fs.writeFileSync(outPath, lines.join('\n'));
  return outPath;
}

function detectMode(source: string): 'class' | 'function' {
  return (source.includes('class ') && (source.includes('@Module') || source.includes('@Sequential') || source.includes('@Combinational') || source.includes('extends Module')))
    ? 'class' : 'function';
}

export function buildFile(inputPath: string, outDir: string): { success: boolean; outPath: string; lines: number } {
  const source = fs.readFileSync(inputPath, 'utf-8');
  const baseName = path.basename(inputPath, '.ts');
  const mode = detectMode(source);

  if (mode === 'class') {
    const result = compileClassModule(source);
    if (!result.success) {
      return { success: false, outPath: '', lines: 0 };
    }
    const outPath = path.join(outDir, baseName + '.sv');
    fs.writeFileSync(outPath, result.systemverilog);
    return { success: true, outPath, lines: result.systemverilog.split('\n').length };
  } else {
    try {
      const tokens = new Lexer(source).tokenize();
      const ast = new Parser(tokens).parse();
      const checker = new TypeChecker();
      const checked = checker.check(ast);
      const emitter = new VerilogEmitter(checked);
      const verilog = emitter.emit(ast);
      const outPath = path.join(outDir, baseName + '.sv');
      fs.writeFileSync(outPath, verilog);
      return { success: true, outPath, lines: verilog.split('\n').length };
    } catch (error: any) {
      return { success: false, outPath: '', lines: 0 };
    }
  }
}

// Main - only run when called directly
if (require.main === module) {
  const command = process.argv[2];
  if (command === 'build') {
    const opts = parseArgs(process.argv.slice(3));
    if (!opts.input) {
      console.error('Usage: ts2v build <file.ts|dir> [--out <dir>] [--board <board.json>]');
      process.exit(1);
    }
    fs.mkdirSync(opts.outDir, { recursive: true });
    console.log(`ts2v build -> ${opts.outDir}`);

    let files: string[] = [];
    if (fs.statSync(opts.input).isDirectory()) {
      files = fs.readdirSync(opts.input).filter((f: string) => f.endsWith('.ts')).map((f: string) => path.join(opts.input, f));
    } else {
      files = [opts.input];
    }

    let success = 0, fail = 0;
    for (const f of files) {
      const r = buildFile(f, opts.outDir);
      if (r.success) { console.log(`  OK ${f} -> ${r.outPath} (${r.lines} lines)`); success++; }
      else { console.error(`  FAIL ${f}`); fail++; }
    }

    if (opts.board) {
      const cst = generateConstraints(opts.board, opts.outDir);
      console.log(`  Constraints: ${cst}`);
    }

    // sim.f
    const svFiles = fs.readdirSync(opts.outDir).filter((f: string) => f.endsWith('.sv'));
    const fPath = path.join(opts.outDir, 'sim.f');
    fs.writeFileSync(fPath, svFiles.map((f: string) => path.join(opts.outDir, f)).join('\n'));
    console.log(`  File list: ${fPath}`);
    console.log(`\nDone: ${success} compiled, ${fail} failed`);
    process.exit(fail > 0 ? 1 : 0);
  } else {
    console.log('ts2v - TypeScript to SystemVerilog Compiler (IEEE 1800-2017)');
    console.log('Commands:');
    console.log('  ts2v build <file.ts|dir> [--out <dir>] [--board <board.json>]');
  }
}
