"use strict";
// String constants and error message templates for the compiler.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ERROR_ARRAY_SIZE_REQUIRED = exports.ERROR_CONST_REASSIGN = exports.ERROR_MISSING_RETURN = exports.ERROR_INVALID_NUMBER = exports.ERROR_UNTERMINATED_STRING = exports.ERROR_EMPTY_SOURCE = exports.ERROR_BIT_WIDTH_MISMATCH = exports.ERROR_UNSUPPORTED_CONSTRUCT = exports.ERROR_DUPLICATE_DECLARATION = exports.ERROR_UNDECLARED_VARIABLE = exports.ERROR_TYPE_MISMATCH = exports.ERROR_UNKNOWN_TYPE = exports.ERROR_EXPECTED_TOKEN = exports.ERROR_UNEXPECTED_TOKEN = exports.VERILOG_DEFAULT_NETTYPE_WIRE = exports.VERILOG_DEFAULT_NETTYPE_NONE = exports.VERILOG_TIMESCALE = exports.VERILOG_HEADER = exports.PRODUCT_DESCRIPTION = exports.PRODUCT_VERSION = exports.PRODUCT_NAME = void 0;
exports.PRODUCT_NAME = 'ts2v';
exports.PRODUCT_VERSION = '2.0.0';
exports.PRODUCT_DESCRIPTION = 'TypeScript to SystemVerilog compiler';
// SystemVerilog output header
exports.VERILOG_HEADER = '// Generated by ts2v - TypeScript to SystemVerilog compiler';
exports.VERILOG_TIMESCALE = '`timescale 1ns / 1ps';
exports.VERILOG_DEFAULT_NETTYPE_NONE = '`default_nettype none';
exports.VERILOG_DEFAULT_NETTYPE_WIRE = '`default_nettype wire';
// Error message templates (use %s for interpolation)
exports.ERROR_UNEXPECTED_TOKEN = 'Unexpected token "%s" at line %d, column %d';
exports.ERROR_EXPECTED_TOKEN = 'Expected "%s" but found "%s" at line %d, column %d';
exports.ERROR_UNKNOWN_TYPE = 'Unknown type "%s" at line %d, column %d';
exports.ERROR_TYPE_MISMATCH = 'Type mismatch: cannot assign "%s" to "%s" at line %d, column %d';
exports.ERROR_UNDECLARED_VARIABLE = 'Undeclared variable "%s" at line %d, column %d';
exports.ERROR_DUPLICATE_DECLARATION = 'Duplicate declaration "%s" at line %d, column %d';
exports.ERROR_UNSUPPORTED_CONSTRUCT = 'Unsupported construct "%s" at line %d, column %d';
exports.ERROR_BIT_WIDTH_MISMATCH = 'Bit-width mismatch: %d-bit value assigned to %d-bit target at line %d, column %d';
exports.ERROR_EMPTY_SOURCE = 'Source file is empty';
exports.ERROR_UNTERMINATED_STRING = 'Unterminated string literal at line %d, column %d';
exports.ERROR_INVALID_NUMBER = 'Invalid numeric literal "%s" at line %d, column %d';
exports.ERROR_MISSING_RETURN = 'Function "%s" must have a return statement';
exports.ERROR_CONST_REASSIGN = 'Cannot reassign const variable "%s" at line %d, column %d';
exports.ERROR_ARRAY_SIZE_REQUIRED = 'Fixed array size required for hardware synthesis at line %d, column %d';
//# sourceMappingURL=strings.js.map